### PR TITLE
User can see self

### PR DESCRIPTION
**Pull request by ChrisJVoss**
screen shot 2017-08-10 at 1 08 09 pm

### CODE REVIEW

**Comment by ChrisJVoss** [comment]
electric-eye-1

**Review by thebearingedge — APPROVED** [review]
Is it possible to link photon from a cdn?

**Comment by ChrisJVoss** [comment]
I don't believe so. Neither Alvin nor I found one. There is a photon.min.css which is ~20% smaller.

**Comment by thebearingedge** [comment]
Ok, no worries

- Tim

**Pull request merged**
